services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: haj-apps-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DEBUG: "False"

    volumes:
      - ./staticfiles:/app/config/staticfiles

    networks:
      - hajapp-backend-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: haj-apps-nginx
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
    networks:
      - hajapp-backend-network

networks:
  hajapp-backend-network:
    driver: bridge
